spring:
  application:
    name: olivefit

  datasource:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${DB_USER}&password=${DB_PASSWORD}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

bezkoder:
  app:
    jwtSecret: VjIzNFRuQWx6UkdyUGJhblBtT3Z1a2Rtd1dEZ3NURzNWVnlZMEtHZG9KZA==
    jwtExpirationMs: 86400000

server:
  tomcat:
    max-threads: 300  # 최대 스레드 수 (기본 200 → 300으로 늘림)
    min-spare-threads: 50  # 최소 스레드 수


management:
  endpoints:
    web:
      exposure:
        include: "metrics", "health", "threadpool"
