spring:
  application:
    name: olivefit

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cosmetics}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}   # ????? ???? ??? ???? ? ???
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa: #db? ??? ???? ??? ?? ?? ?????
    hibernate: #JPA? ???? ???
      ddl-auto: update #hibernate? db? ??? ???? ??.
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

