# .github/workflows/ci-backend.yml
name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
         
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Gradle Build 
        run: |
          cd olivefit_back
          chmod +x ./gradlew
          ./gradlew clean test   