# .github/workflows/ci-backend.yml
name: Flutter CI

on:
  push:
    paths:
      - 'olivefit_front/**'
  pull_request:
    paths:
      - 'olivefit_front/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Analyze
        run: |
          cd olivefit_front
          flutter pub get
          flutter analyze || true
      