version: "3.8"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olivefit_app
    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-postgres:5432/cosmetics
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
    networks:
      - olivefit-net

networks:
  olivefit-net:
    external: true

